runtime: nodejs20
instance_class: F1
service: teacher-backend

automatic_scaling:
  min_idle_instances: 0
  max_concurrent_requests: 80

env_variables:
  NODE_ENV: production
  PORT: 8080
  DATABASE_URL: "postgresql://tsuser:tsuser1234@/geobukschool_dev?host=/cloudsql/ts-back-nest-479305:asia-northeast3:geobuk-db&schema=teacher_admin&search_path=teacher_admin,hub,tutorboard"
  AUTH_SECRET: "AIetry5Dr+7rPJBj01hYdoKT0gxBk28JD8PPJVEQSa4MBnPGMAwH7tkSUx0BLaBRSysleQlcuSXLLeox0nVhTg=="

beta_settings:
  cloud_sql_instances: ts-back-nest-479305:asia-northeast3:geobuk-db
