runtime: nodejs20
instance_class: F1
service: teacher-backend

automatic_scaling:
  min_idle_instances: 0
  max_concurrent_requests: 80

env_variables:
  NODE_ENV: production
  PORT: 8080
  DATABASE_URL: "postgresql://tsuser:tsuser1234@/geobukschool_prod?host=/cloudsql/ts-back-nest-479305:asia-northeast3:geobuk-db&schema=teacher_admin&search_path=teacher_admin,hub,tutorboard,susi,jungsi,mysanggibu"
  AUTH_SECRET: "04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1"

beta_settings:
  cloud_sql_instances: ts-back-nest-479305:asia-northeast3:geobuk-db
