/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const StudentsLazyRouteImport = createFileRoute('/students')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const MessagesLazyRouteImport = createFileRoute('/messages')()
const StudentsStudentIdLazyRouteImport = createFileRoute(
  '/students/$studentId',
)()

const StudentsLazyRoute = StudentsLazyRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/students.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const MessagesLazyRoute = MessagesLazyRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/messages.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdLazyRoute = StudentsStudentIdLazyRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsLazyRoute,
} as any).lazy(() =>
  import('./routes/students.$studentId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/messages': typeof MessagesLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/students': typeof StudentsLazyRouteWithChildren
  '/students/$studentId': typeof StudentsStudentIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/messages': typeof MessagesLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/students': typeof StudentsLazyRouteWithChildren
  '/students/$studentId': typeof StudentsStudentIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/messages': typeof MessagesLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/students': typeof StudentsLazyRouteWithChildren
  '/students/$studentId': typeof StudentsStudentIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/messages'
    | '/settings'
    | '/students'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/messages' | '/settings' | '/students' | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/messages'
    | '/settings'
    | '/students'
    | '/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessagesLazyRoute: typeof MessagesLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  StudentsLazyRoute: typeof StudentsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdLazyRouteImport
      parentRoute: typeof StudentsLazyRoute
    }
  }
}

interface StudentsLazyRouteChildren {
  StudentsStudentIdLazyRoute: typeof StudentsStudentIdLazyRoute
}

const StudentsLazyRouteChildren: StudentsLazyRouteChildren = {
  StudentsStudentIdLazyRoute: StudentsStudentIdLazyRoute,
}

const StudentsLazyRouteWithChildren = StudentsLazyRoute._addFileChildren(
  StudentsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessagesLazyRoute: MessagesLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  StudentsLazyRoute: StudentsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
